name: Omlet CLI Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:

    - name: Run Omlet analysis
      env:
        OMLET_TOKEN: ${{ secrets.OMLET_TOKEN }}
      run: yarn dlx @omlet/cli analyze
